apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appp
  template:
    metadata:
      name: appp
      labels:
        app: appp
    spec:
      containers:
        - image: alialkady/a2
          name: nginx
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
    
