apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
  labels:
    app: appp
    name: AliAlkady
spec:
  containers:
    - name: a2
      image: nginx:alpine
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"
      







